// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZaYkevI5hr2cpXd8XzOCs3JkT6_k_LH4',
    appId: '1:39170698212:web:ec4925c65cba9422db75f1',
    messagingSenderId: '39170698212',
    projectId: 'ca-attendance-c3e5a',
    authDomain: 'ca-attendance-c3e5a.firebaseapp.com',
    storageBucket: 'ca-attendance-c3e5a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzOUydSoMdHerOCAHGtzDTO4o6h7gm2pk',
    appId: '1:39170698212:android:7afaafee0ba01335db75f1',
    messagingSenderId: '39170698212',
    projectId: 'ca-attendance-c3e5a',
    storageBucket: 'ca-attendance-c3e5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpOfiK9pOcDnS5iMaS1kp36O6ZoPzqgI0',
    appId: '1:39170698212:ios:ce60e70f161d5d07db75f1',
    messagingSenderId: '39170698212',
    projectId: 'ca-attendance-c3e5a',
    storageBucket: 'ca-attendance-c3e5a.firebasestorage.app',
    iosBundleId: 'com.example.caAttendence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpOfiK9pOcDnS5iMaS1kp36O6ZoPzqgI0',
    appId: '1:39170698212:ios:ce60e70f161d5d07db75f1',
    messagingSenderId: '39170698212',
    projectId: 'ca-attendance-c3e5a',
    storageBucket: 'ca-attendance-c3e5a.firebasestorage.app',
    iosBundleId: 'com.example.caAttendence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZaYkevI5hr2cpXd8XzOCs3JkT6_k_LH4',
    appId: '1:39170698212:web:7d1384c0cc545421db75f1',
    messagingSenderId: '39170698212',
    projectId: 'ca-attendance-c3e5a',
    authDomain: 'ca-attendance-c3e5a.firebaseapp.com',
    storageBucket: 'ca-attendance-c3e5a.firebasestorage.app',
  );
}
